### ISSUE TITLE
Possibility to set zoomLevelInPresentationMode value

### ISSUE THREAD

**Issue by PixelT** [jspolancor/presentation-mode#1]
Please add a possibility to change the value of `zoomLevelInPresentationMode` in user settings.
If the value `zoomLevelInPresentationMode` can be set up as `1`, we maybe can achieve this functionality: https://github.com/Microsoft/vscode/issues/16927

Maximize current pane as it is on:
Atom -> https://github.com/santip/maximize-panes
SublimeText -> https://github.com/jisaacks/MaxPane

**Comment by PixelT** [comment]
Oh, now I see it doesn't work when we have layout n+1 column... would be good if in presentation mode we can show current pane in whole window width as 1 column view - it is possible?

**Comment by jspolancor** [comment]
Hi! I'm currently working on the `zoomLevelInPresentationMode` in user settings. 
I think showing the current pane as 1 column is possible, but it should be optional too, as a boolean in the user settings, maybe `oneColumnInPresentationMode: true`? Thanks for the suggestions.

**Comment by jspolancor** [comment]
It's ready in the 1.1.2 version. I'm closing this issue.
I just opened a new one for the one pane thing #2
