### ISSUE TITLE
Ability to disable ESC for quitting presentation mode

### ISSUE THREAD

**Issue by everdrone** [jspolancor/presentation-mode#3]
Would be nice to have another option (or just by running the command again) to exit presentation mode.

the escape key may be pressed quite a lot, especially when dealing with intellisense

**Comment by everdrone** [comment]
whoops, could've waited a minute more.
sorry for that, just found out the option in the keybindings file

**Comment by texastoland** [comment]
@jspolancor I can't imagine a scenario I use <kdb>escape</kdb> (multi-select for example) while demo-ing code. Could the default be changed? I recommend <kdb>escape</kdb> <kdb>escape</kdb> to match Zen Mode.
