### ISSUE TITLE
"command 'extension/presentationModeExit' not found" while using Zen Mode

### ISSUE THREAD

**Issue by pzelnip** [jspolancor/presentation-mode#4]
With this extension installed, periodically I get a ```command 'extension/presentationModeExit' not found``` toast notification while working with VS Code's Zen mode.

See screenshot:

![screen shot 2018-05-11 at 2 18 46 pm](https://user-images.githubusercontent.com/414933/39947330-57b85da0-5526-11e8-9da1-0650ff3f7987.png)

VS Code version: 1.23.1
OS: OSX (Sierra)
Presentation-mode version: 1.1.3

**Comment by jspolancor** [comment]
Hi man, Thanks for reporting the issue.
Yeah the presentation mode triggers the zen mode, and it's suppossed to close on esc key, I will fix this tomorrow.
Cheers

**Comment by jspolancor** [comment]
Fixed on 1.1.4
